name: Auto

on:
  schedule:
    - cron: "0 23 * * *"  # CST 早上 7 点 -> UTC 23 点
    - cron: "0 1 * * *"   # CST 早上 9 点 -> UTC 1 点
    - cron: "0 4 * * *"   # CST 中午 12 点 -> UTC 4 点
  workflow_dispatch:

env:
  COOKIE: ${{ secrets.COOKIE }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
          echo "Update at: $(date +'%Y%m%d%H%M%S')" >> UPDATE
          ls -a
      - uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: action
          author_email: action@gh.com
          committer_name: action
          committer_email: action@gh.com
          message: "Update ..."
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
